# generated by datamodel-codegen:
#   filename:  ConnectorSpecification.yml
#   timestamp: 2024-05-09T12:51:09+00:00

from __future__ import annotations

from typing import Optional

from pydantic import AnyUrl, BaseModel, Field


class ConnectionSpecification(BaseModel):
    dat_name: Optional[str] = Field(
        None, description='Name of the actor instance.', title='Name'
    )


class ConnectorSpecification(BaseModel):
    class Config:
        extra = 'allow'

    documentation_url: Optional[AnyUrl] = None
    name: str = Field(
        ...,
        description='The name of the specific connector to which this ConnectorSpecification belongs.',
    )
    module_name: str = Field(
        ..., description='Name of the python module for this connector'
    )
    connection_specification: ConnectionSpecification
