# generated by datamodel-codegen:
#   filename:  ConnectorSpecification.yml
#   timestamp: 2024-04-01T12:46:28+00:00

from __future__ import annotations

from typing import Any, Dict, Optional

from pydantic import AnyUrl, BaseModel, Field


class ConnectorSpecification(BaseModel):
    class Config:
        extra = 'allow'

    documentation_url: Optional[AnyUrl] = None
    name: str = Field(
        ...,
        description='The name of the specific connector to which this ConnectorSpecification belongs.',
    )
    module_name: str = Field(
        ..., description='Name of the python module for this connector'
    )
    connection_specification: Dict[str, Any] = Field(
        ...,
        description='ConnectorDefinition specific blob. Must be a valid JSON string.',
    )
