# generated by datamodel-codegen:
#   filename:  DatDocumentStream.yml
#   timestamp: 2024-03-19T12:20:43+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class SyncMode(Enum):
    full_refresh = 'full_refresh'
    incremental = 'incremental'


class DatDocumentStream(BaseModel):
    class Config:
        extra = 'allow'

    name: str
    namespace: Optional[str] = Field(
        None, description='namespace the data is associated with'
    )
    json_schema: Optional[Dict[str, Any]] = None
    dir_uris: Optional[List[str]] = None
    sync_mode: SyncMode
    cursor_field: Optional[str] = Field(
        None,
        description='Path to the field that will be used to determine if a record is new or modified since the last sync. This field is REQUIRED if `sync_mode` is `incremental`. Otherwise it is ignored.',
    )
