# generated by datamodel-codegen:
#   filename:  DatCatalog.yml
#   timestamp: 2024-01-05T12:37:33+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel
from dat_core.pydantic_models.dat_document_stream import DatDocumentStream

class DatCatalog(BaseModel):
    document_streams: List[DatDocumentStream]
