# generated by datamodel-codegen:
#   filename:  StreamMetadata.yml
#   timestamp: 2024-01-04T11:34:14+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class StreamMetadata(BaseModel):
    class Config:
        extra = 'allow'

    dat_source: str
    dat_stream: str
    dat_record_id: str
    dat_run_id: str
    dat_document_entity: Optional[str] = None
    dat_last_modified: Optional[int] = None
    dat_document_chunk: Optional[str] = None
    dat_run_id: str
