# DEP VectorizeCatalog:
description: Specification of Configured Dat Catalog
type: object
required:
  - document_streams
properties:
  document_streams:
    type: array
    items:
      "$ref": "./ConfiguredDocumentStream.yml"