---
name: Feature Request
description: Suggest a feature for dat-core
labels: ["kind:enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature for dat-core!
        If you like to discuss your idea first, please join our [Slack](https://join.slack.com/t/dat-labs/shared_invite/zt-23wh57yhx-3kAdu022NJjabn8M25qTxA)
        and pose your questions in the #technical-help channel.
        For minor features and improvements, feel free to open a [pull request](https://github.com/dat-labs/dat-core/pulls) directly.
  - type: textarea
    attributes:
      label: Feature description
      description: Describe the feature you'd like to see.
      placeholder: >
        What would you like to happen?
  - type: dropdown
    attributes:
      label: Are you a dat user?
      description: Please tell us how you are using dat-core.
      multiple: false
      options:
        - "Yes, I'm already a dat-core user."
        - "Yes, I run dat-core in production."
        - "Yes, I use it for fun."
        - "I'd consider using dat-core, but it's lacking a feature I need."
  - type: textarea
    attributes:
      label: Use case
      description: Is your feature request related to a problem? Please describe.
      placeholder: >
        What problem are you trying to solve?
  - type: textarea
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like to see.
      placeholder: >
        What would you like to see changed?
  - type: textarea
    attributes:
      label: Related issues
      description: Is there currently another issue associated with this?
