# generated by datamodel-codegen:
#   filename:  ConfiguredDocumentStream.yml
#   timestamp: 2024-01-05T12:33:35+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, List, Optional

from pydantic import BaseModel, Field
from pydantic_models.dat_document_stream import DatDocumentStream, SyncMode


class ConfiguredDocumentStream(BaseModel):
    class Config:
        extra = 'allow'

    stream: DatDocumentStream
    sync_mode: SyncMode
    cursor_field: Optional[List[str]] = Field(
        None,
        description='Path to the field that will be used to determine if a record is new or modified since the last sync. This field is REQUIRED if `sync_mode` is `incremental`. Otherwise it is ignored.',
    )
    primary_key: Optional[List[List[str]]] = Field(
        None,
        description='Paths to the fields that will be used as primary key. This field is REQUIRED if `destination_sync_mode` is `*_dedup`. Otherwise it is ignored.',
    )
