# generated by datamodel-codegen:
#   filename:  Connection.yml
#   timestamp: 2024-01-08T09:44:40+00:00

from __future__ import annotations
from typing import Optional

from pydantic import BaseModel, Field
from pydantic_models.connector_specification import ConnectorSpecification
from pydantic_models.dat_catalog import DatCatalog


class Generator(BaseModel):
    spec: ConnectorSpecification


class Destination(BaseModel):
    spec: ConnectorSpecification


class Source(BaseModel):
    spec: ConnectorSpecification
    catalog: DatCatalog


class Spec(BaseModel):
    source: Source
    generator: Generator
    destination: Destination


class Connection(BaseModel):
    class Config:
        extra = 'allow'

    protocol_version: Optional[str] = Field(
        None,
        description='the Vectorize Protocol version supported by the connector. Protocol versioning uses SemVer.',
    )
    spec: Spec = Field(
        ...,
        description='ConnectorDefinition specific blob. Must be a valid JSON string.',
    )
