# generated by datamodel-codegen:
#   filename:  DatCatalog.yml
#   timestamp: 2023-12-01T08:13:08+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel


class SyncMode(Enum):
    full_refresh = 'full_refresh'
    incremental = 'incremental'


class DocumentStream(BaseModel):
    name: str
    dir_uris: Optional[List[str]] = None
    sync_mode: SyncMode


class DatCatalog(BaseModel):
    document_streams: List[DocumentStream]
