# generated by datamodel-codegen:
#   filename:  DatConnectionStatus.yml
#   timestamp: 2023-12-05T16:32:10+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Status(BaseModel):
    type: str
    enum: List[str]


class Message(BaseModel):
    type: str


class Properties(BaseModel):
    status: Status
    message: Message


class Model(BaseModel):
    description: str
    type: str
    additionalProperties: bool
    required: List[str]
    properties: Properties
