# generated by datamodel-codegen:
#   filename:  StreamMetadata.yml
#   timestamp: 2024-01-03T07:53:57+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class Model(BaseModel):
    class Config:
        extra = 'allow'

    source: str
    stream: str
    data_entity: Optional[str] = None
    retrieved_at: Optional[int] = None
    document_chunk: Optional[str] = None
